### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by msalahz** [jfgiraud/sandr#2]
I got this error when I run the following command `python sandr.py -e -s BONjour -r helLO -i aaa` to test sandr.py

```
  File "sandr.py", line 76
    print(message, file=sys.stderr)
                       ^
SyntaxError: invalid syntax
```

can anyone help ?

**Comment by jfgiraud** [comment]
Hello,
You should use python3.
Under ArchLinux, the default version of python is python3.
